### ISSUE TITLE
Error: An error occurred while fetching Plex movie data: Attempted to divide by zero.

### ISSUE THREAD

**Issue by Naldjer** [GingerSnap96/Radarr-To-Plex-Collections#10]
Hello,

At first i want to thank you for this amazing tool! It was really something i needed in my inventory! :)

Ive configured the config file as described. Tried to run the .EXE, and got the error above.

My setup:

Plex running on a Truenas server;
Radarr running on a Windows VM;

Using the Windows X64 V1.0.3 from the Releases section.

thanks in advance.

Kind regards,

Naldjer

**Comment by GingerSnap96** [comment]
download this and change the extension from .zip to .7z to access the files. GitHub doesn't support 7z but this is the only way i can get it under 25mb (another GitHub limitation). Let me know if this resolves the divide by 0 error.
[win-x64.zip](https://github.com/user-attachments/files/18031314/win-x64.zip)

**Comment by Naldjer** [comment]
Hi @GingerSnap96 

Changing the extension from ZIP to 7Z and extract it then does solve the issue with the ZIP file you provided in here. 
Many thanks!

Regards,

Naldjer
