### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by BlueBull010** [GingerSnap96/Radarr-To-Plex-Collections#12]
I didn't know how else to reach you, since the Reddit thread (https://www.reddit.com/r/radarr/comments/1azf40k/sync_collections_to_plex) has been archived. Just wanted to say thank you for creating this! It worked perfectly from the first go, which is quite rare with these kinds of homemade tools. I set up the config file, fired up the executable and it just went through my thousands of movies (freely downloadable documentaries of course, alongside my Linux ISO collection) and it didn't miss a single one. Simply awesome. Good job! 

You should put a donation link somewhere. Just a suggestion. People (like myself) are often willing to donate a small amount for open source tools they find particularly handy and/or well-made

[**_Edit_**]
Oh by the way, you mention having to use the Radarr v3 API but I'm running Radarr v4 (so I assume that means it's the v4 API as well?) and it works perfectly for that, too. So it doesn't seem to matter which API version you have, it just works for both the most recent versions

**Comment by GingerSnap96** [comment]
Let me say, this made my day. I appreciate your kind words and I'm glad you found the application useful. As for a donation link, having people use what i create is reward enough for me :) 

Also, the radarr application is version 4 but the API itself is still on version 3 as can be found [here](https://radarr.video/docs/api/).
