### ISSUE TITLE
LibraryName setting in config.json

### ISSUE THREAD

**Issue by splatcosmo** [GingerSnap96/Radarr-To-Plex-Collections#2]
Neophyte, sorry... using Win11 system, cannot figure out how to correctly render the "LibraryName" setting in config.json

All other settings seem OK. I've tried several options with no luck. Thanks

**Comment by GingerSnap96** [comment]
Happy to assist, could you provide your config.json (with plex and radarr tokens removed) so I can review for potential issues? Also, have you reviewed the output log for any potential error messages? The log file gets created in a logs folder where the application runs from.

**Comment by splatcosmo** [comment]
Here ya go, thanks. I checked the log files to correct the info up until the "LibraryName" point. I just can't figure out what to name it.

[log-2024-02-27_14-55-07.txt](https://github.com/GingerSnap96/Radarr-To-Plex-Collections/files/14425525/log-2024-02-27_14-55-07.txt)
[config.json](https://github.com/GingerSnap96/Radarr-To-Plex-Collections/files/14425526/config.json)

**Comment by GingerSnap96** [comment]
Looks like it doesn't find that library within your plex server. Library name should be the name of the library within plex that contains your movies. Verify the name of the library and that it is set to a "Movie" library type, this setting is found under Manage > Libraries > {LibraryName}

<img width="548" alt="2024-02-27_15h56_55" src="https://github.com/GingerSnap96/Radarr-To-Plex-Collections/assets/60375885/6c177e87-c331-4bf4-854e-04fa1d5468e7">

**Comment by splatcosmo** [comment]
Thanks. Yes, I have a library named "Movies" (with U.S.-based feature films) and another called "Cinema" (which includes foreign films and other stuff). I've tried both, with and without quotes. Both libraries are indeed set to the "Movie" type.

**Comment by GingerSnap96** [comment]
Try opening the following URL (with your token) in a browser and look at the values in the title field. Verify there are no hidden characters / spaces or better yet, directly copy the value into the config.json. http://localhost:32400/library/sections?X-Plex-Token=YOURTOKEN
<img width="1130" alt="2024-02-27_16h42_27" src="https://github.com/GingerSnap96/Radarr-To-Plex-Collections/assets/60375885/ffe71b88-b312-4db5-a2e2-9eab7a7d921f">

**Comment by splatcosmo** [comment]
Thanks and apologies, been AFK. This is pulling up Plex music libraries, but no movie ones. I have two servers, and I think it's trying to pull from the music server rather than the movie/TV server. I'll play with it a bit more and see what I can figure out.

**Comment by splatcosmo** [comment]
Tried plugging in the Plex token from the movies server, but still got the error. Then I tried doing it on another machine (where the second server is based) and it seems to be working. I may have to add Radarr to that 2nd machine to get wanted results, but consider this fixed for the time being. I appreciate your help and the work you've put into this.

**Comment by GingerSnap96** [comment]
Glad you got it figured out! keep in mind that you do not need to run this application directly on the machine you have plex or radarr. You can instead reference the IP address of the machine on your local network. Change Localhost to the ip address and keep the port for the service and you should get the results you expect!
