### ISSUE TITLE
Remove collection as part of the name?

### ISSUE THREAD

**Issue by Krispkiwi** [GingerSnap96/Radarr-To-Plex-Collections#5]
Hey,

Thanks very much for the tool, I was just wondering if it was possible to remove "Collection" as part of the library name. The main reason I want to do this is that these are already under the collections page in my server so It's sort of double handling on the titles.

It's a small thing but just wondering

**Comment by GingerSnap96** [comment]
Thank you for the feedback! I have updated the application to include this feature, it is available in release "radarr-to-plex-v1.0.2". To remove "collection" from the end of the collection name set "ShortenCollectionName" to true in the config.json.
