### ISSUE TITLE
Are auto descriptions possible?

### ISSUE THREAD

**Issue by Krispkiwi** [GingerSnap96/Radarr-To-Plex-Collections#6]
I've noticed whilst it correctly pulls the radarr collections over, the descriptions of the collections radarr includes don't come with it, do you have any plans to include this?

**Comment by GingerSnap96** [comment]
Thank you for the feedback! I have updated the application to include this feature, it is available in release "radarr-to-plex-v1.0.2". Note that the description is set when the collection is created so you will need to re-create the collections which can be done by setting "DeleteExistingPlexCollections" to true in the config.json.
