### ISSUE TITLE
Attempted to divide by zero Error

### ISSUE THREAD

**Issue by Krispkiwi** [GingerSnap96/Radarr-To-Plex-Collections#8]
Hey, I'm getting this error now however in that closed incident where someone had it previously, they only link to a now dead link.

Did anyone happen to see the fix before it was deleted?

**Comment by Krispkiwi** [comment]
Done some testing, It's able to remove collections from plex so it does have that connection, also tried resetting the radarr api
[log-2024-11-22_12-26-19.txt](https://github.com/user-attachments/files/17853698/log-2024-11-22_12-26-19.txt)
[config.json](https://github.com/user-attachments/files/17853702/config.json)

**Comment by GingerSnap96** [comment]
What OS are you running on? I have an updated version for you to test before i publish it

**Comment by Krispkiwi** [comment]
> What OS are you running on? I have an updated version for you to test before i publish it

Windows with radarr and plex both running on synology's container manager.

**Comment by GingerSnap96** [comment]
download this and change the extension from .zip to .7z to access the files. GitHub doesnt support 7z but this is the only way i can get it under 25mb (another github limitation). Let me know if this resolves the divide by 0 error.
[win-x64.zip](https://github.com/user-attachments/files/17853976/win-x64.zip)

**Comment by Krispkiwi** [comment]
> download this and change the extension from .zip to .7z to access the files. GitHub doesnt support 7z but this is the only way i can get it under 25mb (another github limitation). Let me know if this resolves the divide by 0 error. [win-x64.zip](https://github.com/user-attachments/files/17853976/win-x64.zip)

This has resolved it.
